# docker build -t snailoba/dishdive:??????? .
Docker File

FROM oven/bun:1

WORKDIR /app

# install openssl
RUN apt-get update -y && apt-get install -y openssl

COPY bun.* package.json ./

RUN bun install

COPY . .

EXPOSE 5000

CMD [ "bun", "run", "start" ]
